# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(419, 793)
        self.centralwidget = QtWidgets.QWidget(MainApp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lnedt_Post = QtWidgets.QLineEdit(self.centralwidget)
        self.lnedt_Post.setGeometry(QtCore.QRect(10, 130, 351, 31))
        self.lnedt_Post.setObjectName("lnedt_Post")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 201, 31))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.btn_KisileriCek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_KisileriCek.setGeometry(QtCore.QRect(30, 610, 171, 51))
        self.btn_KisileriCek.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.btn_KisileriCek.setObjectName("btn_KisileriCek")
        self.lnedt_KisiSayisi = QtWidgets.QLineEdit(self.centralwidget)
        self.lnedt_KisiSayisi.setGeometry(QtCore.QRect(10, 220, 351, 31))
        self.lnedt_KisiSayisi.setObjectName("lnedt_KisiSayisi")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 201, 31))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.btn_Sonuclar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sonuclar.setGeometry(QtCore.QRect(210, 610, 171, 51))
        self.btn_Sonuclar.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.btn_Sonuclar.setObjectName("btn_Sonuclar")
        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(210, 680, 171, 51))
        self.btn_Cikis.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.btn_Cikis.setObjectName("btn_Cikis")
        self.btn_Sifirla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sifirla.setGeometry(QtCore.QRect(30, 680, 171, 51))
        self.btn_Sifirla.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.btn_Sifirla.setObjectName("btn_Sifirla")
        self.tablo_Katilimcilar = QtWidgets.QTextBrowser(self.centralwidget)
        self.tablo_Katilimcilar.setGeometry(QtCore.QRect(20, 350, 181, 241))
        self.tablo_Katilimcilar.setObjectName("tablo_Katilimcilar")
        self.tablo_Kazananlar = QtWidgets.QTextBrowser(self.centralwidget)
        self.tablo_Kazananlar.setGeometry(QtCore.QRect(220, 350, 181, 241))
        self.tablo_Kazananlar.setObjectName("tablo_Kazananlar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 171, 31))
        self.label_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 310, 171, 31))
        self.label_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        MainApp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainApp)
        self.statusbar.setObjectName("statusbar")
        MainApp.setStatusBar(self.statusbar)

        self.retranslateUi(MainApp)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "ACM"))
        self.label.setText(_translate("MainApp", "ACM Çekiliş Botu"))
        self.label_2.setText(_translate("MainApp", "Instagram Post Linki:"))
        self.btn_KisileriCek.setText(_translate("MainApp", "Kişileri Belirle"))
        self.label_3.setText(_translate("MainApp", "Kazanacak Kişi Sayısı:"))
        self.btn_Sonuclar.setText(_translate("MainApp", "Sonuçları Gör"))
        self.btn_Cikis.setText(_translate("MainApp", "Çıkış"))
        self.btn_Sifirla.setText(_translate("MainApp", "Sıfırla"))
        self.label_4.setText(_translate("MainApp", "Tüm Katılımcılar"))
        self.label_5.setText(_translate("MainApp", "Kazananlar"))
